/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appjugador.vistas;


import appjugador.Sistema;
import appjugador.controllers.partida.PartidaController;
import appjugador.controllers.partida.UIPartida;
import appjugador.tablecarton.CartonCellRenderer;
import appjugador.tablecarton.CartonTableModule;
import dominio.Jugador;
import dominio.TipoFigura;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Santiago
 */
public class FrmPartida extends javax.swing.JFrame implements UIPartida{
    private PartidaController controller;
   
    /**
     * Creates new form FrmPartida
     */
    public FrmPartida() throws RemoteException {
        initComponents();
        setSize(675, 500);
        pnlPartida.setVisible(false);
        controller = new PartidaController(this, Sistema.getFachada());
        this.setTitle("Usuario: " + Sistema.getJugador().getNombreUsuario());
        controller.validarCantJugadoresPartida();
        controller.listarFiguras();
        controller.mostrarCantidadJugares(); 
        controller.mostrarSaldoJugador();         
        pnlPreguntarContinuidad.setVisible(false);
        pnlGanadorPartida.setVisible(false);
        lblEsperando.setVisible(false);   
        lblAnoto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        pnlGanadorPartida = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblGanador = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblSaldoActual = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlPartida = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCartones = new javax.swing.JTable();
        pnlDatosPartida = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblUltimaBolillaSorteada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPozoPartida = new javax.swing.JLabel();
        lblEsperando = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSaldoJugador = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblListaJugadores = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstJugadores = new javax.swing.JList<>();
        lblAnoto = new javax.swing.JLabel();
        pnlPreguntarContinuidad = new javax.swing.JPanel();
        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlLobby = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFiguras = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlGanadorPartida.setBackground(new java.awt.Color(51, 0, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Felicitaciones ganador: ");

        lblGanador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblGanador.setForeground(new java.awt.Color(255, 255, 255));
        lblGanador.setText("lblGanador");

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Saldo actual: ");

        lblSaldoActual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSaldoActual.setForeground(new java.awt.Color(0, 204, 51));
        lblSaldoActual.setText("Saldo");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PARTIDA FINALIZADA ! ! !");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 51));
        jLabel12.setText("$");

        javax.swing.GroupLayout pnlGanadorPartidaLayout = new javax.swing.GroupLayout(pnlGanadorPartida);
        pnlGanadorPartida.setLayout(pnlGanadorPartidaLayout);
        pnlGanadorPartidaLayout.setHorizontalGroup(
            pnlGanadorPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGanadorPartidaLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(110, 110, 110))
            .addGroup(pnlGanadorPartidaLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(pnlGanadorPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGanadorPartidaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGanador))
                    .addGroup(pnlGanadorPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlGanadorPartidaLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSaldoActual)
                            .addGap(164, 164, 164))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGanadorPartidaLayout.setVerticalGroup(
            pnlGanadorPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGanadorPartidaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addGap(51, 51, 51)
                .addGroup(pnlGanadorPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblGanador))
                .addGap(32, 32, 32)
                .addGroup(pnlGanadorPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(lblSaldoActual))
                .addGap(45, 45, 45)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pnlPartida.setBackground(new java.awt.Color(255, 255, 255));

        tableCartones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCartones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCartonesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCartones);

        pnlDatosPartida.setBackground(new java.awt.Color(102, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bolilla Sorteada");

        lblUltimaBolillaSorteada.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblUltimaBolillaSorteada.setForeground(new java.awt.Color(255, 255, 255));
        lblUltimaBolillaSorteada.setText("10");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pozo Partida");

        lblPozoPartida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPozoPartida.setForeground(new java.awt.Color(0, 204, 51));
        lblPozoPartida.setText("Pozo");

        lblEsperando.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEsperando.setForeground(new java.awt.Color(255, 255, 255));
        lblEsperando.setText("Esperando...");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Saldo Jugador");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 51));
        jLabel7.setText("$");

        lblSaldoJugador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSaldoJugador.setForeground(new java.awt.Color(0, 204, 51));
        lblSaldoJugador.setText("Saldo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 51));
        jLabel10.setText("$");

        lblListaJugadores.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblListaJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblListaJugadores.setText("Lista de Jugadores:");

        jScrollPane3.setViewportView(lstJugadores);

        lblAnoto.setForeground(new java.awt.Color(255, 255, 255));
        lblAnoto.setText("Anoto");

        javax.swing.GroupLayout pnlDatosPartidaLayout = new javax.swing.GroupLayout(pnlDatosPartida);
        pnlDatosPartida.setLayout(pnlDatosPartidaLayout);
        pnlDatosPartidaLayout.setHorizontalGroup(
            pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPartidaLayout.createSequentialGroup()
                .addGroup(pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosPartidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEsperando))
                    .addGroup(pnlDatosPartidaLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblPozoPartida))
                    .addGroup(pnlDatosPartidaLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblSaldoJugador)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosPartidaLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosPartidaLayout.createSequentialGroup()
                        .addGroup(pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnlDatosPartidaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4)))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosPartidaLayout.createSequentialGroup()
                        .addGroup(pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(lblListaJugadores))
                            .addComponent(lblAnoto))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosPartidaLayout.createSequentialGroup()
                        .addComponent(lblUltimaBolillaSorteada)
                        .addGap(85, 85, 85))))
        );
        pnlDatosPartidaLayout.setVerticalGroup(
            pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPartidaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUltimaBolillaSorteada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblPozoPartida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSaldoJugador))
                .addGap(18, 18, 18)
                .addComponent(lblListaJugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblAnoto)
                .addGap(32, 32, 32)
                .addComponent(lblEsperando)
                .addContainerGap())
        );

        pnlPreguntarContinuidad.setBackground(new java.awt.Color(255, 255, 255));

        btnSi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSi.setText("SI");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        btnNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNo.setText("NO");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("¿Desea continuar jugando?");

        javax.swing.GroupLayout pnlPreguntarContinuidadLayout = new javax.swing.GroupLayout(pnlPreguntarContinuidad);
        pnlPreguntarContinuidad.setLayout(pnlPreguntarContinuidadLayout);
        pnlPreguntarContinuidadLayout.setHorizontalGroup(
            pnlPreguntarContinuidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreguntarContinuidadLayout.createSequentialGroup()
                .addGroup(pnlPreguntarContinuidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPreguntarContinuidadLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPreguntarContinuidadLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel5)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        pnlPreguntarContinuidadLayout.setVerticalGroup(
            pnlPreguntarContinuidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPreguntarContinuidadLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlPreguntarContinuidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSi)
                    .addComponent(btnNo))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout pnlPartidaLayout = new javax.swing.GroupLayout(pnlPartida);
        pnlPartida.setLayout(pnlPartidaLayout);
        pnlPartidaLayout.setHorizontalGroup(
            pnlPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPartidaLayout.createSequentialGroup()
                .addGroup(pnlPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPartidaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(pnlPreguntarContinuidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPartidaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(pnlDatosPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlPartidaLayout.setVerticalGroup(
            pnlPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPartidaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(pnlPreguntarContinuidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlDatosPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlLobby.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad de Jugadores:");

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad");

        jScrollPane1.setViewportView(lstFiguras);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Figuras habilitadas para éste juego:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Esperando inicio del juego...");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Saldo del jugador: ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 0));
        jLabel15.setText("$");

        lblSaldo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(51, 204, 0));
        lblSaldo.setText("Saldo");

        javax.swing.GroupLayout pnlLobbyLayout = new javax.swing.GroupLayout(pnlLobby);
        pnlLobby.setLayout(pnlLobbyLayout);
        pnlLobbyLayout.setHorizontalGroup(
            pnlLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLobbyLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(pnlLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLobbyLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaldo))
                    .addComponent(jLabel13)
                    .addComponent(jLabel2)
                    .addGroup(pnlLobbyLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCantidad))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        pnlLobbyLayout.setVerticalGroup(
            pnlLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLobbyLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pnlLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCantidad))
                .addGap(18, 18, 18)
                .addGroup(pnlLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(lblSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlLobby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlGanadorPartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlLobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlGanadorPartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            cerrar();
        } catch (RemoteException ex) {
            Logger.getLogger(FrmPartida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        try {
            controller.continuar();  
            lblEsperando.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(FrmPartida.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        try {
            controller.removerObserver();
            controller.cerrarSesion();
            controller.eliminarJugador();
            System.exit(0);
        } catch (RemoteException ex) {
            Logger.getLogger(FrmPartida.class.getName()).log(Level.SEVERE, null, ex);
        }
        cerrarVentana();
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            controller.removerObserver();
            controller.cerrarSesion();
            controller.eliminarJugador();
            System.exit(0);
        } catch (RemoteException ex) {
            Logger.getLogger(FrmPartida.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tableCartonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCartonesMouseClicked
        if(evt.getClickCount() == 2){
            int row = tableCartones.getSelectedRow();
            int column = tableCartones.getColumnCount();
            
        }
    }//GEN-LAST:event_tableCartonesMouseClicked

    public void cerrar() throws RemoteException{
        int res = JOptionPane.showConfirmDialog(this, "¿Desea cerrar sesión?", "Atención", JOptionPane.YES_NO_OPTION);
        if (res == 0) {
            controller.cerrarSesion();
            controller.eliminarJugador();
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmPartida().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(FrmPartida.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    @Override
    public void mostrarCantJugadores(int n) {
       lblCantidad.setText(String.valueOf(n));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAnoto;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblEsperando;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JLabel lblListaJugadores;
    private javax.swing.JLabel lblPozoPartida;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoActual;
    private javax.swing.JLabel lblSaldoJugador;
    private javax.swing.JLabel lblUltimaBolillaSorteada;
    private javax.swing.JList<Object> lstFiguras;
    private javax.swing.JList<Object> lstJugadores;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel pnlDatosPartida;
    private javax.swing.JPanel pnlGanadorPartida;
    private javax.swing.JPanel pnlLobby;
    private javax.swing.JPanel pnlPartida;
    private javax.swing.JPanel pnlPreguntarContinuidad;
    private javax.swing.JTable tableCartones;
    // End of variables declaration//GEN-END:variables

    @Override
    public void listarFiguras(ArrayList<TipoFigura> f) {
        lstFiguras.setListData(f.toArray());
    }
    
    @Override
    public void listarJugadores(ArrayList<Jugador> jugadores) {
        lstJugadores.setListData(jugadores.toArray());
    }

    @Override
    public void partidaIniciada() {
        pnlPartida.setVisible(true);
        pnlLobby.setVisible(false);  
        setSize(900, 526);    
    }

    @Override
    public void listarCartones(Integer[][] cartones) {
        CartonTableModule modelo = new CartonTableModule(cartones);
        tableCartones.setModel(modelo);
        tableCartones.setDefaultRenderer(Object.class, new CartonCellRenderer());
        tableCartones.setRowHeight(20);      
        tableCartones.setCellSelectionEnabled(true);
        tableCartones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    @Override
    public void mostrarUltimaBolillaSorteada(int n) {
        lblUltimaBolillaSorteada.setText(String.valueOf(n));         
    }

    @Override
    public void preguntarContinuidad() {
          pnlPreguntarContinuidad.setVisible(true);          
    }

    @Override
    public void mostrarPozo(int n) {
        lblPozoPartida.setText(String.valueOf(n));
    }
    
    @Override
    public void mostrarSaldoJugador(int n) {
        lblSaldoJugador.setText(String.valueOf(n));
    }
 

    @Override
    public void cerrarVentana() {
        System.exit(0);
    }

    @Override
    public void ocultarPanelContinuar() {
       pnlPreguntarContinuidad.setVisible(false);       
    }

    @Override
    public void mostrarGanador(String nombre) {
        lblGanador.setText(nombre);
    }

    @Override
    public void mostrarSaldoActual(int n) {
        lblSaldoActual.setText(String.valueOf(n));      
        lblSaldo.setText(String.valueOf(n));
    } 

    @Override
    public void mostrarPanelGanador() {
        pnlPartida.setVisible(false);
        pnlGanadorPartida.setVisible(true);
        setSize(675, 500);
    }   

    @Override
    public void ocultarEsperando() {
        lblEsperando.setVisible(false);
    }  
 
   

   

 
}
