/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appadministrador.vistas;

import appadministrador.Sistema;
import appadministrador.controllers.configuracion.ConfiguracionController;
import appadministrador.controllers.configuracion.UIConfiguracion;
import dominio.Configuracion;
import dominio.TipoFigura;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago
 */
public class FrmConfiguracion extends javax.swing.JFrame implements UIConfiguracion{
    private ConfiguracionController controller;

    /**
     * Creates new form FrmConfiguracion
     */
    public FrmConfiguracion() {
        initComponents();   
        setLocationRelativeTo(null);
        controller = new ConfiguracionController(this, Sistema.getFachada()); 
        try {
            controller.listarConfiguraciones();  
            controller.listarFiguras();  
            controller.cargarSpinnersConfiguracion();
            controller.cargarBotonesFiguras();
        } catch (RemoteException ex) {
            Logger.getLogger(FrmConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardarConfiguracion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstConfiguraciones = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spCantFilas = new javax.swing.JSpinner();
        spCantColumnas = new javax.swing.JSpinner();
        spCantJugadores = new javax.swing.JSpinner();
        spCartonesPorJugador = new javax.swing.JSpinner();
        spValorCarton = new javax.swing.JSpinner();
        rbtnLineal = new javax.swing.JRadioButton();
        rbtnDiagonal = new javax.swing.JRadioButton();
        rbtnCentro = new javax.swing.JRadioButton();
        rbtnCartonLleno = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFiguras = new javax.swing.JList<>();
        spTiempo = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurar Partida");

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Configurar Partida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel2.setText("Configuración Activa");

        jLabel3.setText("Cantidad de Filas");

        jLabel4.setText("Cantidad de Columnas");

        jLabel5.setText("Jugadores por Partida");

        jLabel6.setText("Cartones por Jugador");

        jLabel7.setText("Valor Carton");

        btnGuardarConfiguracion.setText("Guardar Configuración");
        btnGuardarConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConfiguracionActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstConfiguraciones);

        jLabel8.setText("Tiempo de Espera");

        jLabel9.setText("Tipos de Figuras");

        rbtnLineal.setText("Lineal");

        rbtnDiagonal.setText("Diagonal");

        rbtnCentro.setText("Centro");

        rbtnCartonLleno.setSelected(true);
        rbtnCartonLleno.setText("Cartón Lleno");
        rbtnCartonLleno.setEnabled(false);

        jScrollPane2.setViewportView(lstFiguras);

        jLabel10.setText("Figuras Activadas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarConfiguracion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spTiempo)
                                    .addComponent(spValorCarton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(spCartonesPorJugador)
                                    .addComponent(spCantJugadores)
                                    .addComponent(spCantFilas)
                                    .addComponent(spCantColumnas))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnCartonLleno)
                                    .addComponent(rbtnLineal)
                                    .addComponent(rbtnDiagonal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel10))
                                    .addComponent(rbtnCentro))))))
                .addGap(101, 101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spCantFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnLineal)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(spCantJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnDiagonal))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(spCartonesPorJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnCentro)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(spCantColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spValorCarton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtnCartonLleno)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 43, Short.MAX_VALUE)
                .addComponent(btnGuardarConfiguracion)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConfiguracionActionPerformed
        try {
            if(getCantFilas() < 1 || getCantFilas() > 11 ||
                 getCantColumnas() < 0 || getCantColumnas() > 11 ||
                    getCantJugadores() < 2 || getCantJugadores() > 3 ||
                    getCartonesPorJugador() < 0 || getValorCarton() < 0 || getTiempoEspera() < 10){
                 JOptionPane.showMessageDialog(this,"Configuración no válida","Error",JOptionPane.ERROR_MESSAGE);     
            }
            else if(controller.partidaActiva()){
                JOptionPane.showMessageDialog(this,"No se puede modificar la configuración","Hay un juego activo",JOptionPane.ERROR_MESSAGE); 
            }
            else{
                controller.guardarConfiguracion();            
                JOptionPane.showMessageDialog(this, "Configuración guardada");      
                controller.listarConfiguraciones();
                controller.cargarBotonesFiguras();
            } 
        } catch (RemoteException ex) {
            Logger.getLogger(FrmConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarConfiguracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Object> lstConfiguraciones;
    private javax.swing.JList<Object> lstFiguras;
    private javax.swing.JRadioButton rbtnCartonLleno;
    private javax.swing.JRadioButton rbtnCentro;
    private javax.swing.JRadioButton rbtnDiagonal;
    private javax.swing.JRadioButton rbtnLineal;
    private javax.swing.JSpinner spCantColumnas;
    private javax.swing.JSpinner spCantFilas;
    private javax.swing.JSpinner spCantJugadores;
    private javax.swing.JSpinner spCartonesPorJugador;
    private javax.swing.JSpinner spTiempo;
    private javax.swing.JSpinner spValorCarton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void listarConfiguraciones(ArrayList<Configuracion> configuraciones) {
        lstConfiguraciones.setListData(configuraciones.toArray());
    }
    
     @Override
    public void listarFiguras(ArrayList<TipoFigura> f) {
        lstFiguras.setListData(f.toArray());
    }

    @Override
    public int getCantColumnas() {
        return (int) spCantColumnas.getValue();
    }

    @Override
    public int getCantFilas() {
        return (int) spCantFilas.getValue();
    }

    @Override
    public int getCantJugadores() {
        return (int) spCantJugadores.getValue();
    }

    @Override
    public int getCartonesPorJugador() {
        return (int) spCartonesPorJugador.getValue();
    }

    @Override
    public int getValorCarton() {
        return (int) spValorCarton.getValue();
    }
    
    @Override
    public int getTiempoEspera() {
        return (int) spTiempo.getValue();
    }

    @Override
    public boolean getLineal() {
         return rbtnLineal.isSelected();         
    }      

    @Override
    public boolean getDiagonal() {
        boolean activada = rbtnDiagonal.isSelected();
        if((int) spCantColumnas.getValue() == (int) spCantFilas.getValue() && activada){
            return true;
        }
        else if(activada && (int) spCantFilas.getValue() != (int) spCantColumnas.getValue()){
            JOptionPane.showMessageDialog(this,"No se puede activar Diagonal", "Error", JOptionPane.ERROR_MESSAGE); 
            rbtnDiagonal.setSelected(false);
            return false;
        } 
        return activada;
    }
    

    @Override
    public boolean getCentro() {
        boolean activada = rbtnCentro.isSelected();
        if((int) spCantColumnas.getValue() == (int) spCantFilas.getValue() && activada 
                && (int) spCantFilas.getValue() %2 != 0 && (int) spCantColumnas.getValue() %2 != 0){
            return true;
        }
        else if(activada){
            JOptionPane.showMessageDialog(this,"No se puede activar Centro", "Error", JOptionPane.ERROR_MESSAGE); 
            rbtnCentro.setSelected(false);
            return false;
        } 
        return activada;
    }

    @Override
    public void LinealActivado() {
        rbtnLineal.setSelected(true);
    }

    @Override
    public void DiagonalActivado() {
        rbtnDiagonal.setSelected(true);
    }

    @Override
    public void CentroActivado() {
        rbtnCentro.setSelected(true);
    }

    @Override
    public void setCantColumnas(int n) {
        spCantColumnas.setValue(n);
    }

    @Override
    public void setCantFilas(int n) {
        spCantFilas.setValue(n);
    }

    @Override
    public void setCantJugadores(int n) {
        spCantJugadores.setValue(n);
    }

    @Override
    public void setCantCartonesJugador(int n) {
        spCartonesPorJugador.setValue(n);
    }

    @Override
    public void setValorCarton(int n) {
        spValorCarton.setValue(n);
    }

    @Override
    public void setTiempoEspera(int n) {
        spTiempo.setValue(n);
    }

   

  

}

   
   

    
    
    

   



       
